local map_area_config = { -- Indicates the minimum and maximum coordinates of a given area, then assigns the corresponding name
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.cliffs_coast"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.cordinia_town"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.death_mountains"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.east_castle"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.east_lost_woods"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.east_mountains"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.east_swamp"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.eventide_island"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.faron_woods"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.gerudo_desert"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.gerudo_village"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.haunted_forest"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.hylia_lake"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.hyrule_town"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.kakarico_village"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.kokiri_village"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.lonlon_ranch"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.lost_woods"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.miracles_coast"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.north_field"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.north_west_castle"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.parapa_bay"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.parapa_town"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.parapa_valley"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.rito_village"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.ruins"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.snowpeaks"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.south_field"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.swamp"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.west_mountains"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.zora_falls"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.zora_forest"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.zora_river"},
  {x_min = 0, x_max = 0,
  y_min = 0, y_max = 0,
  key = "map.names.out.zora_village"}
  
}

return map_area_config